// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import {
  demos as dm0,
  frontmatter as fm0,
  toc as toc0,
  texts as txt0,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/docs/docs/changelog.md?type=meta';
import {
  demos as dm1,
  frontmatter as fm1,
  toc as toc1,
  texts as txt1,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useArray/index.md?type=meta';
import {
  demos as dm2,
  frontmatter as fm2,
  toc as toc2,
  texts as txt2,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useBoolean/index.md?type=meta';
import {
  demos as dm3,
  frontmatter as fm3,
  toc as toc3,
  texts as txt3,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useClick/index.md?type=meta';
import {
  demos as dm4,
  frontmatter as fm4,
  toc as toc4,
  texts as txt4,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useClickAway/index.md?type=meta';
import {
  demos as dm5,
  frontmatter as fm5,
  toc as toc5,
  texts as txt5,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useClipboardText/index.md?type=meta';
import {
  demos as dm6,
  frontmatter as fm6,
  toc as toc6,
  texts as txt6,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useDebounceFn/index.md?type=meta';
import {
  demos as dm7,
  frontmatter as fm7,
  toc as toc7,
  texts as txt7,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useDynamicList/README.md?type=meta';
import {
  demos as dm8,
  frontmatter as fm8,
  toc as toc8,
  texts as txt8,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useEasyStore/index.md?type=meta';
import {
  demos as dm9,
  frontmatter as fm9,
  toc as toc9,
  texts as txt9,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useElementIsScroll/index.md?type=meta';
import {
  demos as dm10,
  frontmatter as fm10,
  toc as toc10,
  texts as txt10,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useEventListener/index.md?type=meta';
import {
  demos as dm11,
  frontmatter as fm11,
  toc as toc11,
  texts as txt11,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useHash/index.md?type=meta';
import {
  demos as dm12,
  frontmatter as fm12,
  toc as toc12,
  texts as txt12,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useHover/index.md?type=meta';
import {
  demos as dm13,
  frontmatter as fm13,
  toc as toc13,
  texts as txt13,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useIntersectionObserver/index.md?type=meta';
import {
  demos as dm14,
  frontmatter as fm14,
  toc as toc14,
  texts as txt14,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useIntervalFn/index.md?type=meta';
import {
  demos as dm15,
  frontmatter as fm15,
  toc as toc15,
  texts as txt15,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useLockScroll/index.md?type=meta';
import {
  demos as dm16,
  frontmatter as fm16,
  toc as toc16,
  texts as txt16,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useMount/index.md?type=meta';
import {
  demos as dm17,
  frontmatter as fm17,
  toc as toc17,
  texts as txt17,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useMountedState/index.md?type=meta';
import {
  demos as dm18,
  frontmatter as fm18,
  toc as toc18,
  texts as txt18,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useMouse/index.md?type=meta';
import {
  demos as dm19,
  frontmatter as fm19,
  toc as toc19,
  texts as txt19,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useMutationObserver/index.md?type=meta';
import {
  demos as dm20,
  frontmatter as fm20,
  toc as toc20,
  texts as txt20,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useNumber/index.md?type=meta';
import {
  demos as dm21,
  frontmatter as fm21,
  toc as toc21,
  texts as txt21,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useObject/index.md?type=meta';
import {
  demos as dm22,
  frontmatter as fm22,
  toc as toc22,
  texts as txt22,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/usePersistFn/index.md?type=meta';
import {
  demos as dm23,
  frontmatter as fm23,
  toc as toc23,
  texts as txt23,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/usePosition/index.md?type=meta';
import {
  demos as dm24,
  frontmatter as fm24,
  toc as toc24,
  texts as txt24,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/usePrevious/README.md?type=meta';
import {
  demos as dm25,
  frontmatter as fm25,
  toc as toc25,
  texts as txt25,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/usePromise/index.md?type=meta';
import {
  demos as dm26,
  frontmatter as fm26,
  toc as toc26,
  texts as txt26,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useReactive/index.md?type=meta';
import {
  demos as dm27,
  frontmatter as fm27,
  toc as toc27,
  texts as txt27,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useResizeObserver/index.md?type=meta';
import {
  demos as dm28,
  frontmatter as fm28,
  toc as toc28,
  texts as txt28,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useScroll/index.md?type=meta';
import {
  demos as dm29,
  frontmatter as fm29,
  toc as toc29,
  texts as txt29,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useSize/index.md?type=meta';
import {
  demos as dm30,
  frontmatter as fm30,
  toc as toc30,
  texts as txt30,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useStore/index.md?type=meta';
import {
  demos as dm31,
  frontmatter as fm31,
  toc as toc31,
  texts as txt31,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useSyncScroll/README.md?type=meta';
import {
  demos as dm32,
  frontmatter as fm32,
  toc as toc32,
  texts as txt32,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useThrottleFn/index.md?type=meta';
import {
  demos as dm33,
  frontmatter as fm33,
  toc as toc33,
  texts as txt33,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useTimeoutFn/index.md?type=meta';
import {
  demos as dm34,
  frontmatter as fm34,
  toc as toc34,
  texts as txt34,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useTitle/index.md?type=meta';
import {
  demos as dm35,
  frontmatter as fm35,
  toc as toc35,
  texts as txt35,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useToggle/index.md?type=meta';
import {
  demos as dm36,
  frontmatter as fm36,
  toc as toc36,
  texts as txt36,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUnmount/index.md?type=meta';
import {
  demos as dm37,
  frontmatter as fm37,
  toc as toc37,
  texts as txt37,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUpdate/index.md?type=meta';
import {
  demos as dm38,
  frontmatter as fm38,
  toc as toc38,
  texts as txt38,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUpdateEffect/index.md?type=meta';
import {
  demos as dm39,
  frontmatter as fm39,
  toc as toc39,
  texts as txt39,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUpdateLayoutEffect/index.md?type=meta';
import {
  demos as dm40,
  frontmatter as fm40,
  toc as toc40,
  texts as txt40,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUrlState/index.md?type=meta';
import {
  demos as dm41,
  frontmatter as fm41,
  toc as toc41,
  texts as txt41,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useVirtualList/README.md?type=meta';
import {
  demos as dm42,
  frontmatter as fm42,
  toc as toc42,
  texts as txt42,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useVirtualTable/README.md?type=meta';
import {
  demos as dm43,
  frontmatter as fm43,
  toc as toc43,
  texts as txt43,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useVisible/README.md?type=meta';
import {
  demos as dm44,
  frontmatter as fm44,
  toc as toc44,
  texts as txt44,
} from 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useWindowIsScroll/index.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/docs/changelog': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'hooks/useArray/index': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'hooks/useBoolean/index': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'hooks/useClick/index': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'hooks/useClickAway/index': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'hooks/useClipboardText/index': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'hooks/useDebounceFn/index': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'hooks/useDynamicList/README': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'hooks/useEasyStore/index': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'hooks/useElementIsScroll/index': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'hooks/useEventListener/index': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'hooks/useHash/index': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'hooks/useHover/index': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'hooks/useIntersectionObserver/index': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'hooks/useIntervalFn/index': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'hooks/useLockScroll/index': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'hooks/useMount/index': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'hooks/useMountedState/index': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'hooks/useMouse/index': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'hooks/useMutationObserver/index': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'hooks/useNumber/index': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'hooks/useObject/index': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'hooks/usePersistFn/index': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'hooks/usePosition/index': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'hooks/usePrevious/README': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'hooks/usePromise/index': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'hooks/useReactive/index': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'hooks/useResizeObserver/index': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'hooks/useScroll/index': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
  'hooks/useSize/index': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
  'hooks/useStore/index': {
    frontmatter: fm30,
    toc: toc30,
    texts: txt30,
    demos: dm30,
  },
  'hooks/useSyncScroll/README': {
    frontmatter: fm31,
    toc: toc31,
    texts: txt31,
    demos: dm31,
  },
  'hooks/useThrottleFn/index': {
    frontmatter: fm32,
    toc: toc32,
    texts: txt32,
    demos: dm32,
  },
  'hooks/useTimeoutFn/index': {
    frontmatter: fm33,
    toc: toc33,
    texts: txt33,
    demos: dm33,
  },
  'hooks/useTitle/index': {
    frontmatter: fm34,
    toc: toc34,
    texts: txt34,
    demos: dm34,
  },
  'hooks/useToggle/index': {
    frontmatter: fm35,
    toc: toc35,
    texts: txt35,
    demos: dm35,
  },
  'hooks/useUnmount/index': {
    frontmatter: fm36,
    toc: toc36,
    texts: txt36,
    demos: dm36,
  },
  'hooks/useUpdate/index': {
    frontmatter: fm37,
    toc: toc37,
    texts: txt37,
    demos: dm37,
  },
  'hooks/useUpdateEffect/index': {
    frontmatter: fm38,
    toc: toc38,
    texts: txt38,
    demos: dm38,
  },
  'hooks/useUpdateLayoutEffect/index': {
    frontmatter: fm39,
    toc: toc39,
    texts: txt39,
    demos: dm39,
  },
  'hooks/useUrlState/index': {
    frontmatter: fm40,
    toc: toc40,
    texts: txt40,
    demos: dm40,
  },
  'hooks/useVirtualList/README': {
    frontmatter: fm41,
    toc: toc41,
    texts: txt41,
    demos: dm41,
  },
  'hooks/useVirtualTable/README': {
    frontmatter: fm42,
    toc: toc42,
    texts: txt42,
    demos: dm42,
  },
  'hooks/useVisible/README': {
    frontmatter: fm43,
    toc: toc43,
    texts: txt43,
    demos: dm43,
  },
  'hooks/useWindowIsScroll/index': {
    frontmatter: fm44,
    toc: toc44,
    texts: txt44,
    demos: dm44,
  },
};

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
