// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from 'D:/ownerCode/wwhooks/node_modules/.pnpm/dumi@2.1.8_m273yayteyy2vzqmynnb6kpyha/node_modules/dumi/theme-default/slots/PreviewerActions/index.js';
