// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {
      '404': { id: '404', path: '*', parentId: 'DocLayout' },
      'dumi-context-layout': {
        id: 'dumi-context-layout',
        path: '/',
        isLayout: true,
      },
      DocLayout: {
        id: 'DocLayout',
        path: '/',
        parentId: 'dumi-context-layout',
        isLayout: true,
      },
      'docs/guide/index': {
        path: 'guide',
        id: 'docs/guide/index',
        parentId: 'DocLayout',
      },
      'docs/index': { path: '', id: 'docs/index', parentId: 'DocLayout' },
      'components/colSpan/index': {
        id: 'components/colSpan/index',
        path: 'components/col-span',
        parentId: 'DocLayout',
      },
      'components/IsType/index': {
        id: 'components/IsType/index',
        path: 'components/is-type',
        parentId: 'DocLayout',
      },
      'components/setDefaultArguments/index': {
        id: 'components/setDefaultArguments/index',
        path: 'components/set-default-arguments',
        parentId: 'DocLayout',
      },
      'demo-render': {
        id: 'demo-render',
        path: '~demos/:id',
        parentId: 'dumi-context-layout',
        prerender: false,
      },
    },
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.8_m273yayteyy2vzqmynnb6kpyha__node_modules__dumi__dist__client__pages__404" */ 'D:/ownerCode/wwhooks/node_modules/.pnpm/dumi@2.1.8_m273yayteyy2vzqmynnb6kpyha/node_modules/dumi/dist/client/pages/404.js'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */ 'D:/ownerCode/wwhooks/packages/wwutils/.dumi/tmp-production/dumi/theme/ContextWrapper.tsx'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.8_m273yayteyy2vzqmynnb6kpyha__node_modules__dumi__theme-default__layouts__DocLayout__index" */ 'D:/ownerCode/wwhooks/node_modules/.pnpm/dumi@2.1.8_m273yayteyy2vzqmynnb6kpyha/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          ),
      ),
      'docs/guide/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__guide__index.md" */ 'D:/ownerCode/wwhooks/packages/wwutils/docs/guide/index.md'
          ),
      ),
      'docs/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__index.md" */ 'D:/ownerCode/wwhooks/packages/wwutils/docs/index.md'
          ),
      ),
      'components/colSpan/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "colSpan__index.md" */ 'D:/ownerCode/wwhooks/packages/wwutils/src/colSpan/index.md'
          ),
      ),
      'components/IsType/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "IsType__index.md" */ 'D:/ownerCode/wwhooks/packages/wwutils/src/IsType/index.md'
          ),
      ),
      'components/setDefaultArguments/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "setDefaultArguments__index.md" */ 'D:/ownerCode/wwhooks/packages/wwutils/src/setDefaultArguments/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.8_m273yayteyy2vzqmynnb6kpyha__node_modules__dumi__dist__client__pages__Demo__index" */ 'D:/ownerCode/wwhooks/node_modules/.pnpm/dumi@2.1.8_m273yayteyy2vzqmynnb6kpyha/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
    },
  };
}
