// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {
      '404': { id: '404', path: '*', parentId: 'DocLayout' },
      'dumi-context-layout': {
        id: 'dumi-context-layout',
        path: '/',
        isLayout: true,
      },
      DocLayout: {
        id: 'DocLayout',
        path: '/',
        parentId: 'dumi-context-layout',
        isLayout: true,
      },
      'docs/docs/changelog': {
        path: 'docs/changelog',
        id: 'docs/docs/changelog',
        parentId: 'DocLayout',
      },
      'hooks/useArray/index': {
        id: 'hooks/useArray/index',
        path: 'hooks/use-array',
        parentId: 'DocLayout',
      },
      'hooks/useBoolean/index': {
        id: 'hooks/useBoolean/index',
        path: 'hooks/use-boolean',
        parentId: 'DocLayout',
      },
      'hooks/useClick/index': {
        id: 'hooks/useClick/index',
        path: 'hooks/use-click',
        parentId: 'DocLayout',
      },
      'hooks/useClickAway/index': {
        id: 'hooks/useClickAway/index',
        path: 'hooks/use-click-away',
        parentId: 'DocLayout',
      },
      'hooks/useClipboardText/index': {
        id: 'hooks/useClipboardText/index',
        path: 'hooks/use-clipboard-text',
        parentId: 'DocLayout',
      },
      'hooks/useDebounceFn/index': {
        id: 'hooks/useDebounceFn/index',
        path: 'hooks/use-debounce-fn',
        parentId: 'DocLayout',
      },
      'hooks/useDynamicList/README': {
        id: 'hooks/useDynamicList/README',
        path: 'hooks/use-dynamic-list',
        parentId: 'DocLayout',
      },
      'hooks/useEasyStore/index': {
        id: 'hooks/useEasyStore/index',
        path: 'hooks/use-easy-store',
        parentId: 'DocLayout',
      },
      'hooks/useElementIsScroll/index': {
        id: 'hooks/useElementIsScroll/index',
        path: 'hooks/use-element-is-scroll',
        parentId: 'DocLayout',
      },
      'hooks/useEventListener/index': {
        id: 'hooks/useEventListener/index',
        path: 'hooks/use-event-listener',
        parentId: 'DocLayout',
      },
      'hooks/useHash/index': {
        id: 'hooks/useHash/index',
        path: 'hooks/use-hash',
        parentId: 'DocLayout',
      },
      'hooks/useHover/index': {
        id: 'hooks/useHover/index',
        path: 'hooks/use-hover',
        parentId: 'DocLayout',
      },
      'hooks/useIntersectionObserver/index': {
        id: 'hooks/useIntersectionObserver/index',
        path: 'hooks/use-intersection-observer',
        parentId: 'DocLayout',
      },
      'hooks/useIntervalFn/index': {
        id: 'hooks/useIntervalFn/index',
        path: 'hooks/use-interval-fn',
        parentId: 'DocLayout',
      },
      'hooks/useLockScroll/index': {
        id: 'hooks/useLockScroll/index',
        path: 'hooks/use-lock-scroll',
        parentId: 'DocLayout',
      },
      'hooks/useMount/index': {
        id: 'hooks/useMount/index',
        path: 'hooks/use-mount',
        parentId: 'DocLayout',
      },
      'hooks/useMountedState/index': {
        id: 'hooks/useMountedState/index',
        path: 'hooks/use-mounted-state',
        parentId: 'DocLayout',
      },
      'hooks/useMouse/index': {
        id: 'hooks/useMouse/index',
        path: 'hooks/use-mouse',
        parentId: 'DocLayout',
      },
      'hooks/useMutationObserver/index': {
        id: 'hooks/useMutationObserver/index',
        path: 'hooks/use-mutation-observer',
        parentId: 'DocLayout',
      },
      'hooks/useNumber/index': {
        id: 'hooks/useNumber/index',
        path: 'hooks/use-number',
        parentId: 'DocLayout',
      },
      'hooks/useObject/index': {
        id: 'hooks/useObject/index',
        path: 'hooks/use-object',
        parentId: 'DocLayout',
      },
      'hooks/usePersistFn/index': {
        id: 'hooks/usePersistFn/index',
        path: 'hooks/use-persist-fn',
        parentId: 'DocLayout',
      },
      'hooks/usePosition/index': {
        id: 'hooks/usePosition/index',
        path: 'hooks/use-position',
        parentId: 'DocLayout',
      },
      'hooks/usePrevious/README': {
        id: 'hooks/usePrevious/README',
        path: 'hooks/use-previous',
        parentId: 'DocLayout',
      },
      'hooks/usePromise/index': {
        id: 'hooks/usePromise/index',
        path: 'hooks/use-promise',
        parentId: 'DocLayout',
      },
      'hooks/useReactive/index': {
        id: 'hooks/useReactive/index',
        path: 'hooks/use-reactive',
        parentId: 'DocLayout',
      },
      'hooks/useResizeObserver/index': {
        id: 'hooks/useResizeObserver/index',
        path: 'hooks/use-resize-observer',
        parentId: 'DocLayout',
      },
      'hooks/useScroll/index': {
        id: 'hooks/useScroll/index',
        path: 'hooks/use-scroll',
        parentId: 'DocLayout',
      },
      'hooks/useSize/index': {
        id: 'hooks/useSize/index',
        path: 'hooks/use-size',
        parentId: 'DocLayout',
      },
      'hooks/useStore/index': {
        id: 'hooks/useStore/index',
        path: 'hooks/use-store',
        parentId: 'DocLayout',
      },
      'hooks/useSyncScroll/README': {
        id: 'hooks/useSyncScroll/README',
        path: 'hooks/use-sync-scroll',
        parentId: 'DocLayout',
      },
      'hooks/useThrottleFn/index': {
        id: 'hooks/useThrottleFn/index',
        path: 'hooks/use-throttle-fn',
        parentId: 'DocLayout',
      },
      'hooks/useTimeoutFn/index': {
        id: 'hooks/useTimeoutFn/index',
        path: 'hooks/use-timeout-fn',
        parentId: 'DocLayout',
      },
      'hooks/useTitle/index': {
        id: 'hooks/useTitle/index',
        path: 'hooks/use-title',
        parentId: 'DocLayout',
      },
      'hooks/useToggle/index': {
        id: 'hooks/useToggle/index',
        path: 'hooks/use-toggle',
        parentId: 'DocLayout',
      },
      'hooks/useUnmount/index': {
        id: 'hooks/useUnmount/index',
        path: 'hooks/use-unmount',
        parentId: 'DocLayout',
      },
      'hooks/useUpdate/index': {
        id: 'hooks/useUpdate/index',
        path: 'hooks/use-update',
        parentId: 'DocLayout',
      },
      'hooks/useUpdateEffect/index': {
        id: 'hooks/useUpdateEffect/index',
        path: 'hooks/use-update-effect',
        parentId: 'DocLayout',
      },
      'hooks/useUpdateLayoutEffect/index': {
        id: 'hooks/useUpdateLayoutEffect/index',
        path: 'hooks/use-update-layout-effect',
        parentId: 'DocLayout',
      },
      'hooks/useUrlState/index': {
        id: 'hooks/useUrlState/index',
        path: 'hooks/use-url-state',
        parentId: 'DocLayout',
      },
      'hooks/useVirtualList/README': {
        id: 'hooks/useVirtualList/README',
        path: 'hooks/use-virtual-list',
        parentId: 'DocLayout',
      },
      'hooks/useVirtualTable/README': {
        id: 'hooks/useVirtualTable/README',
        path: 'hooks/use-virtual-table',
        parentId: 'DocLayout',
      },
      'hooks/useVisible/README': {
        id: 'hooks/useVisible/README',
        path: 'hooks/use-visible',
        parentId: 'DocLayout',
      },
      'hooks/useWindowIsScroll/index': {
        id: 'hooks/useWindowIsScroll/index',
        path: 'hooks/use-window-is-scroll',
        parentId: 'DocLayout',
      },
      'demo-render': {
        id: 'demo-render',
        path: '~demos/:id',
        parentId: 'dumi-context-layout',
        prerender: false,
      },
    },
    routeComponents: {
      '404': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.8_m273yayteyy2vzqmynnb6kpyha__node_modules__dumi__dist__client__pages__404" */ 'D:/ownerCode/wwhooks/node_modules/.pnpm/dumi@2.1.8_m273yayteyy2vzqmynnb6kpyha/node_modules/dumi/dist/client/pages/404.js'
          ),
      ),
      'dumi-context-layout': React.lazy(
        () =>
          import(
            /* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */ 'D:/ownerCode/wwhooks/packages/wwhooks/.dumi/tmp/dumi/theme/ContextWrapper.tsx'
          ),
      ),
      DocLayout: React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.8_m273yayteyy2vzqmynnb6kpyha__node_modules__dumi__theme-default__layouts__DocLayout__index" */ 'D:/ownerCode/wwhooks/node_modules/.pnpm/dumi@2.1.8_m273yayteyy2vzqmynnb6kpyha/node_modules/dumi/theme-default/layouts/DocLayout/index.js'
          ),
      ),
      'docs/docs/changelog': React.lazy(
        () =>
          import(
            /* webpackChunkName: "docs__docs__changelog.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/docs/docs/changelog.md'
          ),
      ),
      'hooks/useArray/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useArray__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useArray/index.md'
          ),
      ),
      'hooks/useBoolean/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useBoolean__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useBoolean/index.md'
          ),
      ),
      'hooks/useClick/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useClick__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useClick/index.md'
          ),
      ),
      'hooks/useClickAway/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useClickAway__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useClickAway/index.md'
          ),
      ),
      'hooks/useClipboardText/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useClipboardText__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useClipboardText/index.md'
          ),
      ),
      'hooks/useDebounceFn/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useDebounceFn__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useDebounceFn/index.md'
          ),
      ),
      'hooks/useDynamicList/README': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useDynamicList__README.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useDynamicList/README.md'
          ),
      ),
      'hooks/useEasyStore/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useEasyStore__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useEasyStore/index.md'
          ),
      ),
      'hooks/useElementIsScroll/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useElementIsScroll__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useElementIsScroll/index.md'
          ),
      ),
      'hooks/useEventListener/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useEventListener__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useEventListener/index.md'
          ),
      ),
      'hooks/useHash/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useHash__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useHash/index.md'
          ),
      ),
      'hooks/useHover/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useHover__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useHover/index.md'
          ),
      ),
      'hooks/useIntersectionObserver/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useIntersectionObserver__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useIntersectionObserver/index.md'
          ),
      ),
      'hooks/useIntervalFn/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useIntervalFn__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useIntervalFn/index.md'
          ),
      ),
      'hooks/useLockScroll/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useLockScroll__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useLockScroll/index.md'
          ),
      ),
      'hooks/useMount/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useMount__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useMount/index.md'
          ),
      ),
      'hooks/useMountedState/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useMountedState__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useMountedState/index.md'
          ),
      ),
      'hooks/useMouse/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useMouse__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useMouse/index.md'
          ),
      ),
      'hooks/useMutationObserver/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useMutationObserver__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useMutationObserver/index.md'
          ),
      ),
      'hooks/useNumber/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useNumber__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useNumber/index.md'
          ),
      ),
      'hooks/useObject/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useObject__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useObject/index.md'
          ),
      ),
      'hooks/usePersistFn/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__usePersistFn__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/usePersistFn/index.md'
          ),
      ),
      'hooks/usePosition/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__usePosition__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/usePosition/index.md'
          ),
      ),
      'hooks/usePrevious/README': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__usePrevious__README.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/usePrevious/README.md'
          ),
      ),
      'hooks/usePromise/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__usePromise__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/usePromise/index.md'
          ),
      ),
      'hooks/useReactive/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useReactive__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useReactive/index.md'
          ),
      ),
      'hooks/useResizeObserver/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useResizeObserver__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useResizeObserver/index.md'
          ),
      ),
      'hooks/useScroll/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useScroll__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useScroll/index.md'
          ),
      ),
      'hooks/useSize/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useSize__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useSize/index.md'
          ),
      ),
      'hooks/useStore/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useStore__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useStore/index.md'
          ),
      ),
      'hooks/useSyncScroll/README': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useSyncScroll__README.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useSyncScroll/README.md'
          ),
      ),
      'hooks/useThrottleFn/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useThrottleFn__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useThrottleFn/index.md'
          ),
      ),
      'hooks/useTimeoutFn/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useTimeoutFn__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useTimeoutFn/index.md'
          ),
      ),
      'hooks/useTitle/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useTitle__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useTitle/index.md'
          ),
      ),
      'hooks/useToggle/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useToggle__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useToggle/index.md'
          ),
      ),
      'hooks/useUnmount/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useUnmount__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUnmount/index.md'
          ),
      ),
      'hooks/useUpdate/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useUpdate__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUpdate/index.md'
          ),
      ),
      'hooks/useUpdateEffect/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useUpdateEffect__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUpdateEffect/index.md'
          ),
      ),
      'hooks/useUpdateLayoutEffect/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useUpdateLayoutEffect__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUpdateLayoutEffect/index.md'
          ),
      ),
      'hooks/useUrlState/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useUrlState__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useUrlState/index.md'
          ),
      ),
      'hooks/useVirtualList/README': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useVirtualList__README.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useVirtualList/README.md'
          ),
      ),
      'hooks/useVirtualTable/README': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useVirtualTable__README.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useVirtualTable/README.md'
          ),
      ),
      'hooks/useVisible/README': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useVisible__README.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useVisible/README.md'
          ),
      ),
      'hooks/useWindowIsScroll/index': React.lazy(
        () =>
          import(
            /* webpackChunkName: "hooks__useWindowIsScroll__index.md" */ 'D:/ownerCode/wwhooks/packages/wwhooks/src/hooks/useWindowIsScroll/index.md'
          ),
      ),
      'demo-render': React.lazy(
        () =>
          import(
            /* webpackChunkName: "nm__.pnpm__dumi_2.1.8_m273yayteyy2vzqmynnb6kpyha__node_modules__dumi__dist__client__pages__Demo__index" */ 'D:/ownerCode/wwhooks/node_modules/.pnpm/dumi@2.1.8_m273yayteyy2vzqmynnb6kpyha/node_modules/dumi/dist/client/pages/Demo/index.js'
          ),
      ),
    },
  };
}
