name: Build and Deploy
on: # 监听 master 分支上的 push 事件
  push:
    branches:
      - doc
      - master
jobs:
  deploy:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: pnpm docs:wwhooks
        # run: pnpm docs:wwutils
      - name: Deploy wwhooks
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PUBLISH_PAGES }}
          publish_dir: ./packages/wwhooks/docs-dist
      # - name: Deploy wwutils
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.PUBLISH_PAGES }}
      #     publish_dir: ./wwutils/docs-dist
